name: 'mobiledeviceadmin'
version: 0.0.1
description: A web app built using polymer.dart.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements:
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.0
  analyzer: 0.27.2
  google_maps: ">=2.0.0 <3.1.0"
  custom_elements:
    git: git://github.com/dam0vm3nt/custom_elements.git

transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
